resources:
  limits:
    cpus: 4.0
    memory: 8192

network:
  host_network: false
  server_port:
    port_number: 2222
    bind_mode: published
  additional_ports:
    - name: ssh
      port_number: 2222
      protocol: tcp
      bind_mode: published

run_as:
  user: 568
  group: 568

ix_volumes:
  data: /mnt/hashcat

storage:
  data:
    type: ix_volume
    ix_volume_config:
      dataset_name: data
      create_host_path: true
  additional_storage: []

cuda_hashcat:
  additional_envs: []
